//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Caso_de_Estudio.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reservacion
    {
        public int id { get; set; }
        public int idpersona { get; set; }
        public int tipoR { get; set; }
        public int pcReservacion { get; set; }
        public System.DateTime fecha { get; set; }
        public Nullable<System.TimeSpan> horaEntrada { get; set; }
        public Nullable<System.TimeSpan> horaSalida { get; set; }
        public string observacion { get; set; }
    
        public virtual Computadora Computadora { get; set; }
        public virtual Usuario Usuario { get; set; }
        public virtual TipoReservacion TipoReservacion { get; set; }
    }
}
