//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Caso_de_Estudio.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VW_Permisos
    {
        public int idUser { get; set; }
        public string username { get; set; }
        public string rolName { get; set; }
        public int idRolOpciones { get; set; }
        public string nombreOpcion { get; set; }
        public string descripcionOpcion { get; set; }
    }
}
