//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Caso_de_Estudio.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VW_reservacion
    {
        public string nombreTipoR { get; set; }
        public string descripcion { get; set; }
        public System.DateTime fecha { get; set; }
        public Nullable<System.TimeSpan> horaEntrada { get; set; }
        public Nullable<System.TimeSpan> horaSalida { get; set; }
        public string observacion { get; set; }
        public string caracteristicas { get; set; }
        public string nombre { get; set; }
        public string nombreLab { get; set; }
    }
}
